#!/bin/bash                                                                                            
      
DBLIST=`</srv/config/all.dblist`
CMD=$1                                                                 
shift
                                                                                                       
for x in $DBLIST; do                                                                                   
    echo -----------------------------------------------------------------                             
    echo $x                                                           
    echo -----------------------------------------------------------------                             
    php -ddisplay_errors=On /srv/mediawiki/master/$CMD --wiki $x "${@}" | sed -u "s/^/$x:  /"
done 
