#!/bin/sh
find . -type d -name .git -exec sh -c "cd \"{}\"/../ && pwd && git checkout master && git pull --rebase origin master" \;
find . -type f -name .git -exec sh -c "cd \"{}\"/../ && pwd && git checkout master && git pull --rebase origin master" \;
