#!/bin/bash
DBLIST=`<$1`
BRANCH=$2
shift
shift

for x in $DBLIST; do
	if [ $(mysql -N -s -u root -D $x -e "select count(*) from sites") -eq 0 ]; then
		/usr/bin/php /srv/mediawiki/$BRANCH/maintenance/runScript.php /srv/mediawiki/$BRANCH/extensions/WikidataBuild/extensions/Wikibase/lib/maintenance/populateSitesTable.php --wiki $x --strip-protocols -load-from http://meta.wikimedia.org/w/api.php
	fi

	if [ $(mysql -N -s -u root -D $x -e "select count(*) from interwiki") -eq 0 ]; then
		/usr/bin/php /srv/mediawiki/$BRANCH/maintenance/runScript.php /srv/mediawiki/$BRANCH/extensions/WikidataBuild/extensions/Wikibase/client/maintenance/populateInterwiki.php --wiki $x
	fi	
done
